name: "Publish Weekly Issue"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  undraft:
    name: "Release Draft"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  crosspost:
    name: Auto Crosspost
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout Automation Tool
        uses: actions/checkout@v4
        with:
          repository: MCSR-Weekly/automation

      - name: Build Automation Tool
        run: cargo build --workspace --all-features --all-targets

#      - name: Run Automation Tool
#        run: cargo run --bin crosspost -- ${{jobs.setup.outputs.a}}
